### ISSUE TITLE
Missing delivery person app

### ISSUE THREAD

**Issue by NicksWeatherley** [NicksWeatherley/cuisine-alacarte#5]
The project is missing the delivery person app. 

To Fix:
1. Run `python manage.py startapp delivery_person`
2. Create a file called `urls.py'
3. Add `'delivery_person.apps.DeliveryPersonConfig',` to `INSTALLED_APPS` list in file `cuisine_alacarte/settings.py`

**Comment by nataliaharrow** [comment]
Created deliveryperson app and added it to settings.py
