### ISSUE TITLE
Missing customer app

### ISSUE THREAD

**Issue by NicksWeatherley** [NicksWeatherley/cuisine-alacarte#7]
The project is missing the customer app

To Fix:

1. Run `python manage.py startapp customer`
2. Create a file called `urls.py` in the `customer` directory
3. Add `'customer.apps.CustomerConfig',` to `INSTALLED_APPS` list in file `cuisine_alacarte/settings.py`

**Comment by nataliaharrow** [comment]
created customer app and added it to settings.py
